//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMBusService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trip
    {
        public trip()
        {
            this.tripStops = new HashSet<tripStop>();
        }

        [ScaffoldColumn(false)]
        public int tripId { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Start Time")]
        [Required(ErrorMessage = "Please select start time")]
        public int routeScheduleId { get; set; }

        [Display(Name = "Trip Date")]
        [Required(ErrorMessage = "Please enter trip date")]
        [Range(typeof(DateTime), "1/1/2014", "2/2/2016", ErrorMessage = "Enter date between 1/1/2014 to 2/2/2016")]
        public System.DateTime tripDate { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Driver")]
        [Required(ErrorMessage = "Please select driver")]
        public int driverId { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Bus #")]
        [RegularExpression("^[1-9][0-9]*$", ErrorMessage = "Please select bus number")]
        public int busId { get; set; }


        [Display(Name = "Comments")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Please provide comment")]
        public string comments { get; set; }

        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual routeSchedule routeSchedule { get; set; }
        public virtual ICollection<tripStop> tripStops { get; set; }
    }
}
